name: Release Extension

on:
  push:
    tags:
      - 'v*'   # e.g., v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Package VS Code extension
        run: |
          npm install -g vsce
          vsce package -o vscode-commitgen.vsix

      - name: Upload .vsix to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: vscode-commitgen.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
